# Generated by Django 5.0.1 on 2024-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techn_app', '0003_remove_author_author_author_is_active_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
