# Generated by Django 5.0.1 on 2024-01-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Techn_app', '0004_book_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
