# Generated by Django 5.0.1 on 2024-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techn_app', '0006_author_email_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
