# Generated by Django 5.0.1 on 2024-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techn_app', '0007_book_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.CharField(default=None, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
