# Generated by Django 5.0.1 on 2024-01-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techn_app', '0008_book_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
